# Generated by Django 4.0.4 on 2022-05-24 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_wishlist_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='numarul_de_utilizatori_ce_au_adaugat_produsul',
            field=models.IntegerField(default=0),
        ),
    ]
