# Generated by Django 4.0.4 on 2022-05-24 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_item_numarul_de_utilizatori_ce_au_adaugat_produsul'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='numarul_de_utilizatori_ce_au_adaugat_produsul',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
